INSERT INTO conx.ENVIRONMENT (ENVIRONMENT_ID, ENVIRONMENT_NAME) VALUES (1, 'alpha');
INSERT INTO conx.ENVIRONMENT (ENVIRONMENT_ID, ENVIRONMENT_NAME) VALUES (2, 'staging');
INSERT INTO conx.ENVIRONMENT (ENVIRONMENT_ID, ENVIRONMENT_NAME) VALUES (3, 'production');
INSERT INTO conx.ENVIRONMENT (ENVIRONMENT_ID, ENVIRONMENT_NAME) VALUES (0, 'default');