INSERT INTO conx.PROPERTY_SOURCE (PROPERTY_SOURCE_ID, PROPERTY_SOURCE_NAME) VALUES (1, 'example-spring-cloud-client');
INSERT INTO conx.PROPERTY_SOURCE (PROPERTY_SOURCE_ID, PROPERTY_SOURCE_NAME) VALUES (2, 'example-spring-cloud-client-alpha');
INSERT INTO conx.PROPERTY_SOURCE (PROPERTY_SOURCE_ID, PROPERTY_SOURCE_NAME) VALUES (3, 'xxx-database');
INSERT INTO conx.PROPERTY_SOURCE (PROPERTY_SOURCE_ID, PROPERTY_SOURCE_NAME) VALUES (4, 'boss');